### PR TITLE
add blocked sites

### LINKED ISSUE #1: Unblock extension from doing actions on certain sites.
I need to figure out how to set it so this extension doesn't block these sites if they have the words, coronavirus, covid or covid-19:

https://github.com
https://google.com

### PR DESCRIPTION
**Pull request by TechStudent11**
Fixes #1

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
@TechStudent11 Thanks, I'll do a test before I merge this though.

**Comment by KendallDoesCoding** [comment]
@TechStudent11 I tested it and I'm getting this error on chrome. I don't think its working.... It's not blocking coronavirus or covid or covid-19 anywhere on google.

Uncaught TypeError: blocked.contains is not a function.

This code is highlighted for the error:
if (!blocked.contains(window.location.href)) {

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
Not working on google.

**Comment by KendallDoesCoding** [comment]
Idk how to fix this though. 

@TechStudent11 I removed the code from this PR, and it started working again. So I think google is having some issue reading this line of code:
if (!blocked.contains(window.location.href)) {

**Comment by TechStudent11** [comment]
@KendallDoesCoding fixed

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding fixed

Thanks, I'll do testing

**Review by KendallDoesCoding — APPROVED** [review]

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
No, it's not working still. Atleast with my version of chrome. Please do the testing needed before submitting.

**Comment by KendallDoesCoding** [comment]
@TechStudent11 I made this PR a draft. While you complete testing.

**Comment by KendallDoesCoding** [comment]
@TechStudent11 , chrome gives this error on your code!

script.js:4 (anonymous function)
highlights: else {

**Comment by KendallDoesCoding** [comment]
Ok, I'll do the testing shortly. Thanks

**Comment by KendallDoesCoding** [comment]
@TechStudent11 Just tested, well it runs now but it doesn't un-block the word coronavirus on Github.

**Comment by TechStudent11** [comment]
@KendallDoesCoding How can I view what's happening with the Chrome extension? I tried to inspect the pop-up window but that's not what I'm looking for.

**Comment by KendallDoesCoding** [comment]
Read th README.md for setup.

**Comment by KendallDoesCoding** [comment]
the*

**Comment by TechStudent11** [comment]
@KendallDoesCoding no I want to *INSPECT* it. I want to see the console.

**Comment by KendallDoesCoding** [comment]
Load the extension, if any erros it will show on that page. Otherwise, go
to a site Inspect, Sources and sometimes errors in extension come in
console. Other, then that there's no way except for testing code :(

**Comment by TechStudent11** [comment]
Well it works as Wintended
image

Poopface-19 pandemic lol

**Comment by TechStudent11** [comment]
Sadly I can't inspect the extension. Can't figure out what's going on. I'm gonna make this a draft until I find out how it works.

**Comment by KendallDoesCoding** [comment]
No problem :). Thanks for trying to help. I already made this a draft so dw
about that.

**Comment by KendallDoesCoding** [comment]
> Well it works as Wintended
> 
> image
> 
> Poopface-19 pandemic lol

Well, did you highlight all this text or does it just show??? In Chrome you need to highlight it. This extension is made for chrome not edge lol.

**Comment by KendallDoesCoding** [comment]
Also, you got 5376 Microsoft Points, that catches my eye. Do you want to use them or no? You can get some cool stuff.

**Comment by TechStudent11** [comment]
@KendallDoesCoding No, I didn't highlight it. It just does that. I'm using Edge Chromium so there should be no difference. Yeah I have 5k+ MS Points because I use Bing. There. Roast me all you want. But it's (Bing, not roasting) totally fine (Bing, not roasting). I didn't know you could stuff from them tho. I just thought they were something to keep users on Bing to increase their points. Better look into it.

**Comment by KendallDoesCoding** [comment]
It's okay. I'm a chrome guy but ok lol. Ok that's a edge problem then, you
need to highlight it in chrome. Which country you live in, you can redeem
stuff in these countries  United States, the United Kingdom, France,
Germany, Canada, Australia, New Zealand, Singapore, Republic of Ireland,
Brazil, Italy, Netherlands, Norway, Spain, Sweden, Belgium, Hong Kong SAR,
Japan, Mexico and Taiwan. I think you live around the US so yeah.

**Comment by KendallDoesCoding** [comment]
I wanted some stuff, but I don't live in any of those countries and when I used a VPN I kinda got suspended lol.

**Comment by KendallDoesCoding** [comment]
Closing due to inactivity.

**Pull request closed without merging**
